In [1]:
from sklearn.neighbors import KNeighborsClassifier

In [2]:
import json
import numpy as np

def Face_Assessment():
    STD=0
    YAWNING=1
    TALKING=2
    def __init__(self, file_name):
        # load data from json file
        with open(file_name) as f:
            data = json.load(f)

        std = data['1']
        yawning = data['2']
        talking = data['3']

        # create training data
        X = []
        y = []

        lips = "lips"
        left_eye = "left_eye"
        right_eye = "right_eye"

        std_arr = np.transpose(np.array([std[lips], std[left_eye], std[right_eye]]))
        yawning_arr = np.transpose(np.array([yawning[lips], yawning[left_eye], yawning[right_eye]]))
        talking_arr = np.transpose(np.array([talking[lips], talking[left_eye], talking[right_eye]]))

        STD=0
        YAWNING=1
        TALKING=2

        for i in std_arr:
            X.append(i)
            y.append(STD)
        for i in yawning_arr:
            X.append(i)
            y.append(YAWNING)
        for i in talking_arr:
            X.append(i)
            y.append(TALKING)

        neigh = KNeighborsClassifier(n_neighbors=5)
        self.detector = neigh.fit(X, y)

    def assess(self, lips, left_eye, right_eye):
        arr = np.array([lips, left_eye, right_eye])
        return self.detector.predict(arr)


[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 

TESTING 


In [5]:

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.9)

from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn import neighbors, datasets, preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
print(y_train)
scaler = preprocessing.StandardScaler().fit(X_train)
Xtrain = scaler.transform(X_train)
Xtest = scaler.transform(X_test)

knn = neighbors.KNeighborsClassifier(n_neighbors=5)
knn.fit(Xtrain, y_train)
y_pred = knn.predict(Xtest)

print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(y_pred)

[1, 0, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 1, 1, 2, 2, 2, 1, 0, 0, 0, 2, 2, 2, 0, 0, 2, 2, 2, 2, 1, 1, 2, 2, 1, 2]
0.9338235294117647
              precision    recall  f1-score   support

           0       0.91      0.86      0.89        95
           1       1.00      0.92      0.96        91
           2       0.92      0.97      0.94       222

    accuracy                           0.93       408
   macro avg       0.94      0.92      0.93       408
weighted avg       0.94      0.93      0.93       408

[[ 82   0  13]
 [  1  84   6]
 [  7   0 215]]
[1 2 2 2 0 0 0 2 2 0 0 2 1 0 2 1 0 2 0 1 0 2 0 2 1 2 0 2 1 2 0 2 0 1 2 2 1
 2 2 0 1 2 1 2 0 2 2 2 2 0 2 2 0 2 2 0 1 2 2 0 1 0 2 2 2 2 1 0 2 2 0 1 2 2
 1 2 0 1 2 2 2 2 1 2 1 2 0 2 0 2 2 2 2 2 0 2 2 2 2 1 2 1 0 1 2 1 1 0 0 2 1
 2 2 2 2 1 1 1 0 2 1 2 2 2 2 1 2 2 2 2 1 2 1 0 2 1 2 0 2 0 2 2 0 2 2 2 2 0
 2 2 1 2 1 2 1 0 0 0 2 1 2 2 2 2 0 1 2 1 2 0 0 1 1 0 2 0 2 2 1 1 0 2 2 2 2
 2 2 2 2 0 0 0 2 1 0 2 2 0 2 2 2 2 0 2 2 2 